### PR TITLE
Feat/solution part3

### PR DESCRIPTION
**Pull request by galhelner**
This is a pull request for chess part 3

### CODE REVIEW

**Review by excellenteam-scaleup — COMMENTED** [review]
The project is not compilable, please try to clone, compile and execute, afterwards contact me.

עד 7.6

**Comment by galhelner** [comment]
I just checked it again locally in Clion on my laptop and the project is compilable, everything went right and the program is running correctly.

**Comment by excellenteam-scaleup** [comment]
image
the project should compile according to the instructions in the readme file.

**Comment by galhelner** [comment]
I found and resolve that compilation error, it should be fine now.

File: Chess/src/ThreadPool.cpp [hunk 1]
```diff
@@ -0,0 +1,58 @@
+#include "ThreadPool.h"
+
+ThreadPool::ThreadPool(size_t num_threads) : stop_flag(false), active_tasks(0) {
+    for (size_t i = 0; i < num_threads; ++i) {
+        workers.emplace_back([this]() {
+            while (true) {
```
Comment (excellenteam-scaleup) [inline Chess/src/ThreadPool.cpp:6]: bad practice, one should know when does the while loop stops in the declaration.

**Review by excellenteam-scaleup — COMMENTED** [review]
image
There were no time results in auto mode.

image
No recommendation.
